### ISSUE TITLE
dev-promote-prod-from-git-tag orb job should allow for user provided versions

### ISSUE THREAD

**Issue by ebellefontaine** [CircleCI-Public/orb-tools-orb#116]
One of the difficulties I have been facing with the orb-tools dev-promote-prod-from-git-tag job is that I use release-it to generate my github releases, and create git tags and have that integrated into my workflows. 

It would  be nice to be able to provide a parameter to the dev-promote-prod-git-tag job to allows the user to provide their own version 

Example:
```yaml
...
workflows:
   release:
      jobs:
        - create-release: # Calls Release-it to generate github release, and git tag
            filters:
              branches:
                only: master
              tags:
                ignore: /.*/
   deploy:
      jobs:
        - orb-tools/dev-promote-prod-from-git-tag:
            orb-name: <my-org>/<my-orb>
            add-pr-comment: false
            version: ${CIRCLE_TAG} # <-- Something like this
            filters:
              tags:
                only:
                  - /^v*[0-9]+.[0-9]+.[0-9]+$/
              branches:
                ignore: /.*/
```
