### ISSUE TITLE
Specify the job name the orb-tools/local-test-build command executes

### ISSUE THREAD

**Issue by ks888** [CircleCI-Public/orb-tools-orb#12]
Hi,

I'm currently building the CI/CD for my orb. I'm going to use the orb-tools/local-test-build and write the `.circleci/config.yml` like below:

```
version: 2.1
orbs:
  orb-tools: circleci/orb-tools@2
workflows:
  main:
    jobs:
      - orb-tools/test-in-builds:
          orb-location: src/orb.yml
          orb-name: inspecode
          test-steps:
            - orb-tools/local-test-build:
                test-config-location: test/valid.yml
```

The content of `test/valid.yml` is:

```
version: 2.1
workflows:
  main:
    jobs:
      - inspecode/run:
          api_token: "${INSPECODE_API_TOKEN}"
```

When I push these codes, it returns the error like below:

<img width="959" alt="screen shot 2018-11-22 at 11 06 34" src="https://user-images.githubusercontent.com/8448120/48877478-bcf38f00-ee46-11e8-8d7f-c1aeead1e74f.png">

I think `circleci local execute` implicitly assumes the job name is `build`. In this case, I want to run the job `inspecode/run` instead. Is there any way to specify the job name or any workarounds?

**Comment by ganta** [comment]
There is a workaround to replace the name of the job.

Please add the `name` parameter with the value `build` to the workflow job:

```yaml
version: 2.1
workflows:
  main:
    jobs:
      - inspecode/run:
          api_token: "${INSPECODE_API_TOKEN}"
          name: build
```

It replaces the name of the job by `circleci config process`:
https://github.com/CircleCI-Public/orb-tools-orb/blob/007d290b91f9afb510e264992603a4038f4beced/src/%40orb.yml#L128-L130

```yaml
version: 2
jobs:
  build:
    docker:
    - image: ...
    steps:
    - run:
        ...
workflows:
  main:
    jobs:
    - build
  version: 2
```

This allows you to test the job using `circleci local execute`.
https://github.com/CircleCI-Public/orb-tools-orb/blob/007d290b91f9afb510e264992603a4038f4beced/src/%40orb.yml#L131-L133

The `workflows` definition remains, but it is ignored.
