### ISSUE TITLE
Inconsistent reporting of run commands in "review" job

### ISSUE THREAD

**Issue by wyardley** [CircleCI-Public/orb-tools-orb#128]
## Orb version:
11.1.0

## What happened:
I have an orb with multiple "jobs"; RC008 and RCOO9 seem to behave somewhat inconsistently with the "review" job.

`RC008: All Run steps should contain a name`: I have multiple jobs that have run steps without a name, but only a single one shows up, and that is in a file like the second example below where there should be 2 violations, but only one shows up.

`RC009: All Run step's commands should be imported`: Almost all the same items that should be flagging above also fail this check; in this case, they are reported. However, some of the additional detail seems to be missing or confusing:

```
(in test file review.bats, line 160)
  `exit 1' failed
File: "./src/jobs/job1.yml"
Line number: 12
---
---
File: "./src/jobs/job2.yml"
Line number: 15
---
null
---
```

I can't easily throw up a public demo repo, but happy to provide links to examples to Circle employees offline (I'm on the discussion forum under the same account), or provide more details if you're not able to repro it easily.

## Expected behavior:
Given the following two files, the two checks should fail on both (these are also slightly sanitized versions of the ones that cause the output above):

`src/jobs/job1.yml`:
```yaml
description: "Do some things and then `foo bar`"
executor: <<parameters.executor>>
parameters:
  executor:
    description: The name of custom executor to use
    type: executor
    default: wizzle
steps:
  - checkout
  - restore-deps
  - setup-auth
  - run: npm install --no-save
  - save-deps
```

`src/jobs/job2.yml`:
```yaml
description: "Run thing1 (and, optionally, thing2) on code"
executor: <<parameters.executor>>
parameters:
  executor:
    description: The name of custom executor to use
    type: executor
    default: wizzle
  run-thing2:
    description: whether or not to run foo
    type: boolean
    default: true
steps:
  - checkout
  - restore-deps
  - run: npm run thing1
  - when:
      condition: << parameters.run-thing2 >>
      steps:
        run: npm run thing2
```

## Additional Information:
Also, I would love to see RC008 and RC009 retained / usable, but loosened up somewhat (I just have them ignored outright for now) - I see the value of encouraging good practices and failing on missing titles for very long run commands, or failing on long / complicated shell scripts, but IMO it's a bit overkill to require a single command with no interpolation, variables, or other complexity to be turned into a shell script

i.e., 
```yaml
## not getting much value out of linting this IMO
run: npm run eslint
```

vs
```yaml
run: <<include(scripts/script_that_runs_npm_run_eslint.sh)>>
```

The BATS based approach kind of makes sense, but it might be cleaner to build a linter into the CLI that has somewhat more readable output.

Anyway, while I'd frequently do something like

```yaml
run:
   name: Setup stuff
   command: |
      here is
      a very long set of
      commands that I don't
      really want to see all of & 2>&1
```
IMO, for very simple use cases like this:
```yaml
run: npm run foo
```
is probably (in many cases) clearer and easier to understand in both the Circle web UI and in the config itself
```yaml
run:
  name: Run foo on files
  command: npm run foo
```

So, I know the logic would be much harder to do, but would love to see something that will flag examples where these recommended practices will really help in terms of reducing complexity or increasing readability.
