### ISSUE TITLE
Automatic update examples with correct version of the orb

### ISSUE THREAD

**Issue by Gaardsholt** [CircleCI-Public/orb-tools-orb#134]
## Describe Request:
It would be great if we could use a template value/variable to always have the examples show the correct version of the orb.

## Examples:

Instead of writing the examples like this:
```yaml
usage:
  version: 2.1
  orbs:
    my-orb: my-namespace/my-orb@dev:1.2.3
```

We could do something like this:
```yaml
usage:
  version: 2.1
  orbs:
    my-orb: my-namespace/my-orb@${{ORB_VERSION}}
```

**Comment by KyleTryon** [comment]
I am interested. Highly considering this. 

A few questions / considerations.

1. What would you expect to happen if you used `${{ORB_VERSION}}` (we would like use a syntax similar to << orb.prod.version >>) in an orb that was not your own in the situation where more than one orb is used.
2. In the event a major change is made, the usage examples may incorrectly show out-of-date examples.
    a. If you hard code the version numbers we could at least state that usage example is accurate to the version displayed
    b. Counter-point, if you already use an `x.y.z` structure as we often do, there is no reason not to.
3. We may need to consider what will be valid when running `circleci config validate` against the example.
4. Would we want to enforce this as a new "RC" review check?

I think this is feasible. The publish job would use the CircleCI tag when publishing the orb to make an on-the-fly replacement of the template text. I think an expectation would need to be set that this is simply using the tag version in the pipeline and would only be valid on the orb being built, and should not be used on another orb.

## Examples 

![#2da44e](https://via.placeholder.com/15/2da44e/000000?text=+) **GOOD**
```yaml
usage:
  version: 2.1
  orbs:
    my-orb: my-namespace/my-orb@<< orb.prod.version >>
```
---
![#cf222e](https://via.placeholder.com/15/cf222e/000000?text=+) **BAD**
```yaml
usage:
  version: 2.1
  orbs:
    my-orb: my-namespace/my-orb@<< orb.prod.version >>
    jq: circleci/jq@<< orb.prod.version >>
```
It should be possible to warn the user if we know the orb name and namespace, and ensure it is only used on matching lines.
