### ISSUE TITLE
Re-introduce the `attach-workspace` parameter to the `pack` job

### ISSUE THREAD

**Issue by steinwelberg** [CircleCI-Public/orb-tools-orb#173]
## Describe Request:

In the previous major versions of the orb, the pack job (optionally, based on the `attach-workspace` parameter, included the `attach_workspace` step. We were relying on this step as we are building the orb and a custom (Docker) image, used by the orb in the same project. This allowed us to put a placeholder in the orb yaml, and replace it just before running the pack job. 

## Examples:

```yaml
- orb-tools/pack:
    attach-workspace: true
    requires:
      - orb-tools/lint
```

## Supporting Documentation Links:
- https://circleci.com/developer/orbs/orb/circleci/orb-tools?version=10.1.0#jobs-pack

**Comment by KyleTryon** [comment]
Hey @steinwelberg,

Could you give a full example of what you are intending to do? You likely shouldn't need to persist the packed orb YAML, it is also very small and easily re-packed on the fly.

**Comment by steinwelberg** [comment]
Performance is actually not the problem. Our orb project contains, next to the orb, also a Docker image. We have put these 2 things in the same repository deliberately as they belong together and also evolve together. Hence in order to use a tagged version (instead of a sliding tag like `latest` we are updating the orb yaml before we are packing it.

Executor:
```yaml
parameters:
  tag:
    default: __TAG_PLACEHOLDER__
    description: The tag for the image to use.
    type: string
docker:
  - image: repo.example.com/image:<< parameters.tag >>
```

The `__TAG_PLACEHOLDER__` is replaced with the git commit sha by a job before the pack job is executed. However, without the `attach_workspace` step, the repo sources are used, which contain the placeholder instead of the actual tag. Obviously this does not work for us.
