### ISSUE TITLE
Default parameter not used for executor in orb-tools/pack

### ISSUE THREAD

**Issue by rprince-anduril** [CircleCI-Public/orb-tools-orb#192]
## Orb version:
11.6.1

## What happened:
```
Error: Error calling job: 'my-test'
Cannot find a definition for executor named TEST_STRING
```
for job with:
```
parameters:
  executor:
    description: >
      CCI executor to run tests on
    type: string
    default: my-executor

executor: <<parameters.executor>>
```
where `my-executor` is a valid executor, but the default was apparently not used.

## Expected behavior:
The default value of a parameter is validated instead of `TEST_STRING`

## Additional Information:

I worked around this by using an enum, but we will likely add additional executors for cosuming projects that I don't want to force an orb update for.
