### ISSUE TITLE
Allow custom steps / logic prior to publish

### ISSUE THREAD

**Issue by eddiewebb** [CircleCI-Public/orb-tools-orb#212]
## Describe Request:

Customer is publishing single orb to many organizations and using `matrix` to call publish job.

They thought about using `pre-steps` to run some `envsubt` on the yaml before publishing, but since pre-steps run before workspace from prior job is attached, there is nothing to work on.  Pre-step does not support special copmmands like `attach_workspace` so I am suggesting a parameter to `publish` job that is of `steps` type to run after checkout (#211 )/attach worksapce but before publish step.  

```
- existing checkout or attach steps run
- custom steps parameter steps are executed
- existing publish is executed
```

## Examples:

```
workflows:
  lint-pack:
    jobs:
      ...
      - orb-tools/publish:.
          matrix:
            parameters:
              org_name:
                - "org_1/resource_class"
                - "org_2/resource_class"
                - "org_3/resource_class"
              context:  [ orb-publishing ]
              pre_publish_steps:
                 - export ORG_NAME=<<matrix.org_name>>
                 - envsubst '$ORG_NAME' < ${ORB_DIR}/${ORB_FILE} > ${ORB_DIR}/${ORB_FILE}
```
