### ISSUE TITLE
Add ability for setup steps (pre_publish) for e.g Vault integration

### ISSUE THREAD

**Issue by tdeekens** [CircleCI-Public/orb-tools-orb#217]
## Describe Request:

This Orb's functionality are all provided using jobs. They run on their own executor and spin up a new environment. 

Secrets for publishing or commenting on GitHub have to be present as environment variables. These have to be defined in a project or organisation context as otherwise they would be be unavailable in the publish job of this Orb. 

Secrets are not always defined on CircleCI and can also be pulled from a secret management system such as Vault. 

Currently, this Orb has no way to integrate with secrets (at least in a way I know) of such an external tool. 

A solution would be to allow to define steps running before publishing. This could be called pre_publish. These steps would allow integration with eg Vault using the OIDC tokens and can expose secrets on the environment (BASH_ENV) to be later available. 

## Examples:

```yaml
orb-tools/publish:
   - pre_publish:
       - run:
           command: |
              vault kv get...
              echo "" >>> $BASH_ENV
```

This would also allow to follow [this pattern](https://support.circleci.com/hc/en-us/articles/10816400480411-How-to-pass-environment-variables-between-jobs). 

## Supporting Documentation Links:
