### ISSUE TITLE
orb-tools/continue fails

### ISSUE THREAD

**Issue by DBX12** [CircleCI-Public/orb-tools-orb#222]
## Orb version:
```yaml
orbs:
  orb-tools: circleci/orb-tools@12.0
  ```

## What happened:

The step `orb-tools/continue` fails to execute with this message:
```
{"message":"Continuation key has expired. Please run a new pipeline."}ERROR: Response code 409
Failed to continue pipeline. Attempt to retry the pipeline, if the problem persists please open an issue on the Orb-Tools Orb repository: https://github.com/CircleCI-Public/orb-tools-orb
```
Retrying as recommended by the error message results in the same error message. This error occurs since today, the last successful run was yesterday at 16:49 (UTC+2)

## Expected behavior:

The step should continue to work as it did previously.

## Additional Information:

Current `.circleci/config.yml`

```yaml
version: 2.1
setup: true
orbs:
  orb-tools: circleci/orb-tools@12.0
  shellcheck: circleci/shellcheck@3.1
  bats: circleci/bats@1.1

# Filter for release tags.
release-filters: &release-filters
  branches:
    ignore: /.*/
  tags:
    only: /^[0-9]+\.[0-9]+\.[0-9]+$/

workflows:
  lint-pack:
    jobs:
      - orb-tools/lint
      - orb-tools/pack
      - orb-tools/review:
          exclude: RC006
      - shellcheck/check
      - bats/run:
          path: src/tests
          setup-steps:
            - run:
                command: circleci version
            - run:
                name: Install test dependencies
                command: src/tests/setup.sh
      # Triggers the next workflow in the Orb Development Kit.
      - orb-tools/continue:
          pipeline_number: << pipeline.number >>
          vcs_type: << pipeline.project.type >>
          orb_name: changelog
          requires:
            - orb-tools/lint
            - orb-tools/pack
            - orb-tools/review
            - shellcheck/check
            - bats/run
          filters: *release-filters
```
Current `.circleci/test-deploy.yml`
```yaml
version: 2.1
orbs:
  orb-tools: circleci/orb-tools@12.0
  <orb-name>: {}

release-filters: &release-filters
  branches:
    only: master
  tags:
    only: /^[0-9]+\.[0-9]+\.[0-9]+$/

workflows:
  test-deploy:
    jobs:
      - orb-tools/pack:
          filters: *release-filters
      - hold:
          type: approval
      - orb-tools/publish:
          orb_name: redacted-org-name/redacted-orb-name
          vcs_type: << pipeline.project.type >>
          pub_type: production
          requires:
            - orb-tools/pack
            - hold
          context: orb-publishing
          tag_pattern: '^[0-9]+\.[0-9]+\.[0-9]+$'
          filters: *release-filters
```
