### ISSUE TITLE
CircleCI login is required if referencing an orb within an orb that is private

### ISSUE THREAD

**Issue by jenny-miggin** [CircleCI-Public/orb-tools-orb#225]
## Orb version:

12.0.4

## What happened:

When packing an orb that depends on another private orb in their namespace, the command fails as the user needs to log in via the CLI in order to find the specified `org-id`.

When using this job in a workflow: 

```yml
- orb-tools/pack:
    filters: *filters
    org_slug: gh/my-org-slug
```
the job fails:

```bash
Error: failed to get the appropriate org-id: You must log in first.
``` 

## Expected behavior:

The `org-id` can be found, enabling users to add an orb dependancy

## Additional Information:

A workaround to this is to add a `pre-step` to the job, which uses the CLI to log in. This depends on the availability of an API key (`CIRCLECI_API_TOKEN`) within a context

```yml
- orb-tools/pack:
    filters: *filters
    org_slug: gh/my-org-slug
    pre-steps:
      - run:
          command: |
            circleci setup --no-prompt --token "${CIRCLECI_API_TOKEN}"
    context: my-context
```
