### ISSUE TITLE
Add a new validation to the review job to prevent environment variables from being used in their definition

### ISSUE THREAD

**Issue by david-montano-circleci** [CircleCI-Public/orb-tools-orb#246]
## Describe Request:
There is no validation in orbs PRs to prevent environment variable to be used in the job definitions default values.

## Examples:
This is an example of an invalid job definition that should fail in the review step:
```yaml
description: "Save Go modules to cache."
parameters:
  key:
    description: "User-configurable component for cache key. Useful for avoiding collisions in complex workflows."
    type: string
    default: ""
  path:
    description: "Path to cache."
    type: string
    # /home/circleci/go is the GOPATH in the cimg/go Docker image
    default: "/home/circleci/go/pkg/mod"
  project-path:
    description: |
      The path to the directory containing your Go project files: go.mod, go.sum.
      Defaults to $CIRCLE_WORKING_DIRECTORY.
    type: string
    default: $CIRCLE_WORKING_DIRECTORY
steps:
  - save_cache:
      key: v1-<< parameters.key >>-go-mod-{{ arch }}-{{ checksum "go.sum" }}
      key: v1-<< parameters.key >>-go-mod-{{ arch }}-{{ checksum "<< parameters.project-path >>/go.sum" }}
      paths:
        - << parameters.path >>
```
## Supporting Documentation Links:
- example of related reported issue: https://github.com/CircleCI-Public/go-orb/pull/96
