### ISSUE TITLE
trigger-integration-workflow thinks the branch is new

### ISSUE THREAD

**Issue by qruzz** [CircleCI-Public/orb-tools-orb#29]
### Orb version

8.8.0

### What have you done

Having switched my organisation to use CircleCI for our CI/CD needs, I have been working on creating an Orb with the most relevant functionality for my team. While the Orb itself is working, and I have managed to publish the Orb manually (through the CLI), I now wanted to create a circleci config for handling this continued effort.

I have used the https://github.com/CircleCI-Public/orb-tools-orb/tree/master as a guideline for setting it up. While most of it seems to be working, there is a specific issue with the `trigger-integration-workflow` that I have so far been unable to solve or find support on.

### What happened

The issue is, that during this Job, it tries to determine whether the branch on which the config got triggered previously existed or not. To this, it responds that 'yes, `develop` is new and `1050c58dce8663a4b284519684f904252d24f539` is its only commit'.

This is incorrect as the `develop` branch has over 50 commits to its name in our repository. When it then tries to 'finding most recent ancestor commit from any other branch', it `Exited with code 1`.

Here is a link to an example Job that fails:
https://circleci.com/gh/pluralai/circleci-orbs/97

### Expected behavior

When checking wether the branch is new or not, it should evaluate to false or NO, as the branch is already existing.

### Source

```
version: 2.1

orbs:
  orb-tools: circleci/orb-tools@8.8.0
  plural-ai: pluralai/computing@dev:alpha

workflows:
  lint_validate_publish:
    jobs:
      - orb-tools/lint
      - orb-tools/pack:
          requires:
            - orb-tools/lint
          source-dir: computing
      - orb-tools/publish-dev:
          name: 'publish-orb-dev'
          filters:
            branches:
              only: develop
          requires:
            - orb-tools/pack
          context: plural-int
          orb-name: pluralai/computing
          publish-token-variable: 'PUBLISH_TOKEN_VARIABLE'
          validate: true
      - orb-tools/trigger-integration-workflow:
          name: 'trigger-integration-dev'
          filters:
            branches:
              only: develop
          requires:
            - publish-orb-dev
          ssh-fingerprints: 'my_ssh_fingerprint'
```
